### ISSUE TITLE
Segmentation fault when create Sender-Receiver communication

### ISSUE THREAD

**Issue by SaintJackson** [lqvir/APSU-DDH#1]
Hi, 

I cloned the same project 

[real-world-cryprography](https://github.com/real-world-cryprography)
/
[APSU](https://github.com/real-world-cryprography/APSU)

and compiled it successfully with all required dependencies. The compiler version is g++-10. 

Then I followed auto-test.py, and tried to set connections via the subprocesses. However, it reported an error "Segmentation fault (core dumped)" at sender process side, and an error "Failed to create ReceiverDB: Connection reset by peer; Failed to create ReceiverDB: terminating" at the receiver side.

This happened in both running the two cli in a single python script (i.e. run the file /tools/auto-test.py), and in two separate windows.

The detailed error logs are as follows, from a two-separate-running-window case:

```
root@cloud:/APSU/tools# APSU/build/bin/receiver_cli_ddh -d db.csv -t 4 -p /APSU/parameters/16M-1024.json --port 1212
INFO  09:34:41:756.955: /APSU/cli/receiver/receiver.cpp150
INFO  09:34:45:017.582: Setting thread count to 4
INFO  09:34:45:054.216: PSUParams have false-positive probability 2^(-53.2564) per receiver item
INFO  09:34:45:224.479: Start inserting 262144 items in ReceiverDB
INFO  09:34:45:283.485: Found 262144 new items to insert in ReceiverDB
INFO  09:34:45:356.402: /APSU/receiver/apsu/receiver_db.cpp158
INFO  09:34:45:356.541: /APSU/receiver/apsu/receiver_db.cpp187
ERROR 09:34:45:636.510: Failed to create ReceiverDB: Connection reset by peer
ERROR 09:34:45:668.893: Failed to create ReceiverDB: terminating
``` 

AND

```
ubuntu@cloud:/APSU/tools$ /APSU/build/bin/sender_cli_ddh -q query.csv -t 4 -p /APSU/parameters/16M-1024.json --port 1213
INFO  09:34:45:013.833: /APSU/cli/sender/sender.cpp126
INFO  09:34:45:017.649: /APSU/cli/sender/sender.cpp128
INFO  09:34:45:017.746: Connecting to tcp://localhost:1213
INFO  09:34:45:020.116: Successfully connected to tcp://localhost:1213
INFO  09:34:45:020.155: Sending parameter request
INFO  09:34:45:046.908: PSUParams have false-positive probability 2^(-53.2564) per receiver item
INFO  09:34:45:046.930: Received valid parameters
INFO  09:34:45:046.942: Setting thread count to 4
INFO  09:34:45:078.534: Sending APSU query
INFO  09:34:45:080.173: Creating encrypted query for 1024 items
INFO  09:34:45:080.570: /APSU/sender/apsu/utils.cpp17
Segmentation fault (core dumped).
``` 

 Do you have any suggestions for running a successful 2^10 vs. 2^18 -sized PSU case?

Looking forward to your reply : )

**Comment by lqvir** [comment]
Sorry, we have deactivated this repo, and the latest repo is [APSU](https://github.com/real-world-cryprography/APSU). 
For your question, the sender and the receiver must be connected to the same port e.g. `--port 1212`.  
Hope you’re satisfied.

**Comment by SaintJackson** [comment]
> Sorry, we have deactivated this repo, and the latest repo is [APSU](https://github.com/real-world-cryprography/APSU). For your question, the sender and the receiver must be connected to the same port e.g. `--port 1212`. Hope you’re satisfied.

Thank you for the reply! However, it failed to establish a connection though changed to the same ports. The same error occurred.


I will move the issue to the [https://github.com/real-world-cryprography/APSU/tree/43630be8d5d66b31a1651e02f0036f71e836f932](url). Thank you!
